
package com.example.client.greeting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GreetingServiceImplService", targetNamespace = "http://server.example.com/", wsdlLocation = "http://localhost:8080/greeting?wsdl")
public class GreetingServiceImplService
    extends Service
{

    private final static URL GREETINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GREETINGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GREETINGSERVICEIMPLSERVICE_QNAME = new QName("http://server.example.com/", "GreetingServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/greeting?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GREETINGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GREETINGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GreetingServiceImplService() {
        super(__getWsdlLocation(), GREETINGSERVICEIMPLSERVICE_QNAME);
    }

    public GreetingServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GREETINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public GreetingServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GREETINGSERVICEIMPLSERVICE_QNAME);
    }

    public GreetingServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GREETINGSERVICEIMPLSERVICE_QNAME, features);
    }

    public GreetingServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetingServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GreetingServiceImpl
     */
    @WebEndpoint(name = "GreetingServiceImplPort")
    public GreetingServiceImpl getGreetingServiceImplPort() {
        return super.getPort(new QName("http://server.example.com/", "GreetingServiceImplPort"), GreetingServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreetingServiceImpl
     */
    @WebEndpoint(name = "GreetingServiceImplPort")
    public GreetingServiceImpl getGreetingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.example.com/", "GreetingServiceImplPort"), GreetingServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GREETINGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GREETINGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GREETINGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
